Update README.md
learn-anything/alfred-workflows pull request #18
Opened 2019-11-25 23:11 UTC by maxwelljordanwhite

2019-11-25 23:13 UTC, nikitavoloboev commented
The headings shouldn't be changed. The other changes seem fine.

2019-11-25 23:14 UTC, nikitavoloboev commented
Just realized you are the person behind Pacmax, that's awesome.

Just to clarfiy, the headings shouldn't be changed as I want it consistent with [other lists](https://github.com/learn-anything/curated-lists). So best leave it as it is, I don't think it's an issue.

2019-11-26 02:45 UTC, maxwelljordanwhite commented
Hi! How does that look? Please let me know if I should make any other adjustments. 

Love the list, and Learn Anything!

2019-11-26 10:46 UTC, nikivdev requested changes

2019-11-26 10:46 UTC, nikitavoloboev commented on README.md
> +- [GitHub badge](#github-badge)
No need for this, it's not as important to jump to it

2019-11-26 10:47 UTC, nikitavoloboev commented
One comment then I can merge

2019-11-26 11:44 UTC, merged

2019-11-26 11:44 UTC, nikitavoloboev commented
Thanks

2019-11-26 11:45 UTC, maxwelljordanwhite commented
You're welcome